services:
  edu-nginx:
    image: nginx:latest
    container_name: edu-nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - login-api-was
      - login-app-frontend
    networks:
      - login-api-test-net

  login-app-frontend:
    image: login-app-frontend:latest
    container_name: login-app-frontend
    ports:
      - "80"
    networks:
      - login-api-test-net

  login-api-was:
    image: login-api-was:latest
    container_name: login-api-was
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://edu-mysql:3306/edu?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_REDIS_HOST: edu-redis
      OAUTH2_URL_ALLOW-ORIGIN: http://localhost:80
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT-ID: your-restapi-key
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT-URI: http://localhost/api/login/oauth2/kakao
    depends_on:
      - edu-mysql
    restart: always
    networks:
      - login-api-test-net

  edu-mysql:
    image: mysql:latest
    container_name: edu-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=edu
    depends_on:
      - edu-redis
    networks:
      - login-api-test-net

  edu-redis:
    image: redis:latest
    container_name: edu-redis
    ports:
      - "6379:6379"
    networks:
      - login-api-test-net

networks:
  login-api-test-net: {}